### ISSUE TITLE
Add MIT License

### ISSUE THREAD

**Issue by shivtej1505** [scaler-official/first-contributions#1]
We need to add MIT License in this rep.
Learn more here: https://opensource.org/licenses/MIT

**Comment by Hridoy-31** [comment]
Can I please work on this issue ??

**Comment by shivtej1505** [comment]
Hey @Hridoy-31 
@rishavjnv12 have already raised a PR for this

**Comment by Hridoy-31** [comment]
Okay. Thank you ! Please close this issue.

**Comment by joydeep-ib** [comment]
#28
